### ISSUE TITLE
impossibilty to edit left panel

### ISSUE THREAD

**Issue by ft-fk** [hannesfrank/remnote-schedule#16]
maybe I understood something wrong about the use of this plug-in?

![planner](https://user-images.githubusercontent.com/79699896/125834644-539a141f-8a6b-4e5f-a2e4-413e65f60818.gif)

**Comment by hannesfrank** [comment]
Thanks for the GIF @ft-fk It makes it much more clear what the problem is!

The plugin searches for a child of the currently opened document called "Schedule" where you can write the time blocks. You don't have that yet. This is how it should look like:
![image](https://user-images.githubusercontent.com/4137110/126033917-06b1ebbe-d1b6-484f-8c6e-112516ea623f.png)

**Comment by ft-fk** [comment]
Thanks for this @hannesfrank, I feel stupid not paying more attention to your readme ^^ my bad.
